### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by KronosTheLate** [polazarus/typst-svg-emoji#1]
I am missing a readme with some installation instructions. Is that something you could write up?

**Comment by Pandicon** [comment]
I did a bit of trial-and-error and managed to install it. You have two main options: Use it in the typst online editor, or locally. Both of them are pretty similar. You should download the source code, and then copy the relevant files (the json and regex ones, the lib.typ one, and the typst.toml one) into a directory. For local use, take a look at [https://github.com/typst/packages#local-packages](https://github.com/typst/packages#local-packages), if you put the files into `{data-dir}/local/svg-emoji/0.1.0`, then you can use the `#import "@local/svg-emoji:0.1.0": setup-emoji, noto, github` import as given in the example. For the online editor, you can throw these files into a `svg-emoji` folder and then import the library with `#import "./svg-emoji/lib.typ": setup-emoji, noto, github`.
Hope this helps :D

**Comment by KronosTheLate** [comment]
Thanks a bunch. I ended up using some SVG files found online instead of emojis, and they look better anyway. But such installation instruction would do well in the README!

**Comment by Pandicon** [comment]
I made a pull request with that, now it is up to the repo owner to look at it. It would be even better if the package got included into the preview repository, but that's also up to the owner in my opinion.

**Comment by KronosTheLate** [comment]
Agreed. Thanks for looking into it ^_^

**Comment by polazarus** [comment]
Yeah sorry for the late review! I will look at it now

**Comment by polazarus** [comment]
closed with #3
