### ISSUE TITLE
Add a license (e.g. MIT)

### ISSUE THREAD

**Issue by PgBiel** [polazarus/typst-svg-emoji#5]
Hey, thanks for the awesome package!
Could you add a `LICENSE` file with a permissive license, such as MIT or Apache-2.0? This would allow people to freely use and modify your code, and is also a blocker for #4.
Thanks!

**Comment by polazarus** [comment]
done! but it's not the main thing that blocks #4

**Comment by PgBiel** [comment]
Thank you!
